# Generated by Django 5.1.4 on 2026-08-28 07:29

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('code', models.CharField(help_text='Prefix printed on the token, for example A or FEE.', max_length=3, unique=True)),
                ('description', models.CharField(blank=True, max_length=240)),
                ('avg_service_minutes', models.PositiveIntegerField(default=5, help_text='Starting estimate. Real averages replace it once served.')),
                ('daily_token_limit', models.PositiveIntegerField(default=0, help_text='0 means no limit.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('code', models.CharField(help_text='Shown on the board, e.g. C1.', max_length=12, unique=True)),
                ('location', models.CharField(blank=True, max_length=160)),
                ('status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused'), ('closed', 'Closed')], default='closed', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_counters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CounterSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('tokens_served', models.PositiveIntegerField(default=0)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='queues.counter')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counter_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='QueueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('called', 'Called'), ('serving', 'Serving'), ('served', 'Served'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled')], default='waiting', max_length=12)),
                ('priority', models.IntegerField(default=0, help_text='Higher goes first. Use for accessibility or urgent cases.')),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('wait_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('service_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='queues.counter')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries_served', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'queue entries',
                'ordering': ['-priority', 'queued_at'],
            },
        ),
        migrations.AddField(
            model_name='counter',
            name='now_serving',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='queues.queueentry'),
        ),
        migrations.AddField(
            model_name='counter',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='counters', to='queues.service'),
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepting_tokens', models.BooleanField(default=True, help_text='Turn off to stop issuing new tokens everywhere at once.')),
                ('announcement', models.CharField(blank=True, help_text='Shown on the landing page and the public board.', max_length=240)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'system settings',
                'verbose_name_plural': 'system settings',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('guest_name', models.CharField(blank=True, max_length=120)),
                ('guest_phone', models.CharField(blank=True, max_length=32)),
                ('channel', models.CharField(choices=[('web', 'Web'), ('kiosk', 'Kiosk'), ('counter', 'Issued at counter')], default='web', max_length=12)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issued_to', models.ForeignKey(blank=True, help_text='Empty for walk-ins issued at a counter or kiosk.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tokens', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tokens', to='queues.service')),
            ],
            options={
                'ordering': ['-issued_at'],
            },
        ),
        migrations.AddField(
            model_name='queueentry',
            name='token',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='entry', to='queues.token'),
        ),
        migrations.CreateModel(
            name='QueueEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('issued', 'Token issued'), ('called', 'Called to counter'), ('recalled', 'Called again'), ('started', 'Service started'), ('served', 'Service finished'), ('skipped', 'Skipped'), ('cancelled', 'Cancelled'), ('transferred', 'Moved to another counter')], max_length=16)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='queues.counter')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='queues.queueentry')),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['entry', 'at'], name='queues_queu_entry_i_e13858_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['issue_date', 'service'], name='queues_toke_issue_d_568698_idx'),
        ),
        migrations.AddConstraint(
            model_name='token',
            constraint=models.UniqueConstraint(fields=('service', 'issue_date', 'number'), name='unique_token_per_service_day'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['status', 'priority', 'queued_at'], name='queues_queu_status_eff74e_idx'),
        ),
        migrations.AddIndex(
            model_name='queueentry',
            index=models.Index(fields=['counter', 'status'], name='queues_queu_counter_b3064c_idx'),
        ),
    ]
